<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Erp.Domain\Erp.Domain.csproj" />
    <ProjectReference Include="..\Erp.Application\Erp.Application.csproj" />
    <ProjectReference Include="..\Erp.Infrastructure.MySql\Erp.Infrastructure.MySql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>erp-saas-shared-dev-secrets</UserSecretsId>
  </PropertyGroup>

</Project>
